Django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'), 
    path('api/', include('portfolio.urls')),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name='blog'

urlpatterns = [
    path('',render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail')
]

 

portfolio/urls.py
from django.urls import path
from .views import ProjectList, ProjectDetail

urlpatterns = [
    path('projects/', ProjectList.as_view(), name='project-list'),
    path('projects/<int:pk>/', ProjectDetail.as_view(), name='project-detail'),
]

blog/models.py
from django.db import models
import datetime



class Post(models.Model):
    title= models.CharField((""), max_length=50)
    description=models.TextField((""))
    image=models.ImageField((""), upload_to='blog/images', height_field=None, width_field=None, max_length=None)
    date=models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models


class Project(models.Model):
    tools_choices=[
        ('django', 'Django'),
        ('javascript', 'JavaScript'),
        ('html', 'HTML'),
        ('css', 'CSS'),
        ('python', 'Python'),
        ('fastAPI','FastAPI'),
        ('Flask','Flask'),
    ]
    
    title = models.CharField(("Title"), max_length=100,)
    description = models.CharField(("Description"), max_length=250)
    image = models.URLField(("Image URL"), blank=True)
    # image2 = models.ImageField(("Image - (optional)"),upload_to='portfolio/images/', blank=True, null=True)
    url = models.URLField(blank=True)
    tools_box=models.JSONField() 
    # tools_box2=models.CharField(max_length=255,choices=tools_choices, blank=True)
    # tools_box3=models.CharField(max_length=255,choices=tools_choices, blank=True)
    # tools_box4=models.CharField(max_length=255,choices=tools_choices, blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts=Post.objects.all()

    return render(request,"posts.html",{'posts':posts})

def post_detail(request, post_id):
    post=get_object_or_404(Post,pk=post_id)
    return render(request,'post_detail.html', {'post':post})

portfolio/views.py
from rest_framework import generics
from django.shortcuts import render
from .models import Project
from .serializers import ProjectSerializer

# # Create your views here.

# def home(request):
#     projects= Project.objects.all()
#     return render(request, "home.html",{'projects':projects})

class ProjectList(generics.ListCreateAPIView):
    queryset=Project.objects.all()
    serializer_class = ProjectSerializer

class ProjectDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <h2>{{post.title}}</h2>
        <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS  Y'}}</h3>
        <img src="{{post.image.url}}" alt="{{post.title}}" class='img-'>
        <div class="my-4">
            <p>{{post.description|safe}}</p>
        </div>
    </div>
    
{% endblock content %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

    <h1>Posts</h1>

    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-3">
                        <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
                    </div>
                    <div class="col-9">
                        <h2>{{post.title}}</h2>
                        <p>{{post.description |striptags|truncatechars:100 }}</p>
                        <p>{{post.date|date:'M Y'|upper}}</p>
                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
{% endblock content %}

portfolio/templates/home.html
{% extends 'layout.html' %} 


{% block content %}
{% load static %}


  <header>
  </header>
    <main>
      <section class="container">
        <div class="photo">
          {% comment %} <img src="{% static 'portfolio/p.png' %}" alt="Leonardo Rodriguez"> {% endcomment %}
          
        </div>
    
        <div class="description">
          <h1><strong>Leonardo Rodriguez</strong></h1>
          <h3>Python Backend Developer</h3>
          <p>
            I am a Mechatronic Engineer with over six years of experience in various fields of mechatronics, and I am currently pursuing a Master's degree in Artificial Intelligence and Robotics. I have a strong passion for programming and I am seeking an opportunity to align my career focus with my passion for programming, artificial intelligence, and robotics.

            I have a solid foundation in programming languages such as Python, Java, C/C++, and JavaScript, as well as experience with frameworks like Django, Flask, and FastAPI. I am eager to contribute to a team and make a meaningful impact with my experience and enthusiasm for programming.
          </p>

          <div class="social-networks">
              
            <a href="https://www.linkedin.com/in/leonardo-rodriguez-16a941107/" style="text-decoration: none;" target="_blank">
            {% include 'partials/linkedin_logo.html' %}
            </a>

            <a href="https://github.com/Engleonardorm7" target="_blank" >
              {% include 'partials/git_logo.html' %}
            </a>  


          </div>

          <div class ="button">
              <button onclick="window.open('{% static 'portfolio/CV1.2.pdf' %}', '_blank')"
            class="download_button">
            Download CV
            </button>
          </div>
        </div>
      </section>
    </main>
  <div>
    
    
    <section class="project_container" id="section">
      <div class="project">
        <h3 >PROJECTS</h3>
        <p>
          {% comment %}  {% endcomment %}
        </p>
      </div>
      <div class="each-project">
        {% for project in projects %}
        {% comment %} <div class="card-project"> {% endcomment %}
          
          {% comment %} <div class="each-project"> {% endcomment %}
            
            <figure>
              <img src="{{project.image}}" alt="{{project.title}}"/>

              <div class="capa">
                <div class="card-description">
                  <h2>{{project.title }}</h2>
                  
                  <p>{{project.description}}</p>
                </div>
                  
                <div class="logos">
                  {% comment %} <figure> {% endcomment %}
                  {% if project.tools_box == "django" %}              
                    <a class="django" >
                      {% include 'partials/logo_django.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box == "html" %}              
                    <a class="html_logo" >
                      {% include 'partials/html_css_logo.html' %}
                    </a>
                  {% endif %}
                  
                  {% if project.tools_box == "fastAPI" %}              
                    <a class="fastAPI" >
                      {% include 'partials/fastAPI.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box == "Flask" %}              
                    <a class="flask" >
                      {% include 'partials/flask_logo.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box == "python" %}              
                    <a class="django" >
                      {% include 'partials/logo_python.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box == "javascript" %}              
                    <a class="django" >
                      {% include 'partials/logo_javascript.html' %}
                    </a>
                  {% endif %}

{% comment %} -----------------------toolbox2 {% endcomment %}

                  {% if project.tools_box2 == "django" %}              
                    <a class="django" >
                      {% include 'partials/logo_django.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box2 == "html" %}              
                    <a class="html_logo" >
                      {% include 'partials/html_css_logo.html' %}
                    </a>
                  {% endif %}
                  
                  {% if project.tools_box2 == "fastAPI" %}              
                    <a class="fastAPI" >
                      {% include 'partials/fastAPI.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box2 == "Flask" %}              
                    <a class="flask" >
                      {% include 'partials/flask_logo.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box2 == "python" %}              
                    <a class="python" >
                      {% include 'partials/logo_python.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box2 == "javascript" %}              
                    <a class="javascript" >
                      {% include 'partials/logo_js.html' %}
                    </a>
                  {% endif %}
                  {% comment %} _______________toolbox3___________ {% endcomment %}
                  {% if project.tools_box3 == "django" %}              
                    <a class="django" >
                      {% include 'partials/logo_django.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box3 == "html" %}              
                    <a class="html_logo" >
                      {% include 'partials/html_css_logo.html' %}
                    </a>
                  {% endif %}
                  
                  {% if project.tools_box3 == "fastAPI" %}              
                    <a class="fastAPI" >
                      {% include 'partials/fastAPI.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box3 == "Flask" %}              
                    <a class="flask" >
                      {% include 'partials/flask_logo.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box3 == "python" %}              
                    <a class="python" >
                      {% include 'partials/logo_python.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box3 == "javascript" %}              
                    <a class="javascript" >
                      {% include 'partials/logo_js.html' %}
                    </a>
                  {% endif %}

{% comment %} -----------------------toolbox4 {% endcomment %}

                  {% if project.tools_box4 == "django" %}              
                    <a class="django" >
                      {% include 'partials/logo_django.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box4 == "html" %}              
                    <a class="html_logo" >
                      {% include 'partials/html_css_logo.html' %}
                    </a>
                  {% endif %}
                  
                  {% if project.tools_box4 == "fastAPI" %}              
                    <a class="fastAPI" >
                      {% include 'partials/fastAPI.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box4 == "Flask" %}              
                    <a class="flask" >
                      {% include 'partials/flask_logo.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box4 == "python" %}              
                    <a class="python" >
                      {% include 'partials/logo_python.html' %}
                    </a>
                  {% endif %}
                  {% if project.tools_box4 == "javascript" %}              
                    <a class="javascript" >
                      {% include 'partials/logo_js.html' %}
                    </a>
                  {% endif %}




                  {% comment %} </figure> {% endcomment %}
                </div>
                  <div class="logo_git">
                    {% if project.url %}
                    <a href="{{project.url}}" class="btn btn-light rounded-5 btn-sm" target="_blank" >
                      {% include 'partials/git_logo2.html' %}
                    </a>
                    {% endif %}
                  </div>
              </div>
            </figure>
              
            
            
          {% comment %} </div> {% endcomment %}
        {% comment %} </div> {% endcomment %}
        {% endfor %}
      
      
        </div>
      </div>
    </section>
  {% endblock content %}

portfolio/templates/layout.html
{% load static %}
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="name-container">
           <a class="name" style="text-decoration: none; color: #444444;" href="#">
            <span>Leonardo Rodriguez</span>
        </a>
        </div>
        <div class="projects-container">
          <a class="projects" style="text-decoration: none; color: #444444;" href="#section" >
            <span>Projects</span>
          </a>
          
          {% comment %} <a style="text-decoration: none; color: black;" href="logo1"><img src="logo3"></a> {% endcomment %}
        </div>
        <div class="contact-container">
            <a class="contact" style="text-decoration: none; color: #444444;" href="mailto:leonardorm7@hotmail.com">
                <span>Contact</span>
            </a>
        </div>
    </nav>
    

    
    {% block content %}
    
    {% endblock content %}
    

    
</body>
</html>

portfolio/templates/partials/fastAPI.html
<svg
  fill="none"
  height="30"
  width="30"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 154 154"
>
  <circle cx="77" cy="77" fill="#05998b" r="77" />
  <path
    d="M81.375 18.667l-38.75 70H77.5l-3.875 46.666 38.75-70H77.5z"
    fill="#fff"
  />
</svg>

portfolio/templates/partials/git_logo.html
<svg width="30px" height="30px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      
    <title>github [#142]</title>
    <desc>Created with Sketch.</desc>
    <defs>

</defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Dribbble-Light-Preview" transform="translate(-140.000000, -7559.000000)" fill="#444444">
            <g id="icons" transform="translate(56.000000, 160.000000)">
                <path d="M94,7399 C99.523,7399 104,7403.59 104,7409.253 C104,7413.782 101.138,7417.624 97.167,7418.981 C96.66,7419.082 96.48,7418.762 96.48,7418.489 C96.48,7418.151 96.492,7417.047 96.492,7415.675 C96.492,7414.719 96.172,7414.095 95.813,7413.777 C98.04,7413.523 100.38,7412.656 100.38,7408.718 C100.38,7407.598 99.992,7406.684 99.35,7405.966 C99.454,7405.707 99.797,7404.664 99.252,7403.252 C99.252,7403.252 98.414,7402.977 96.505,7404.303 C95.706,7404.076 94.85,7403.962 94,7403.958 C93.15,7403.962 92.295,7404.076 91.497,7404.303 C89.586,7402.977 88.746,7403.252 88.746,7403.252 C88.203,7404.664 88.546,7405.707 88.649,7405.966 C88.01,7406.684 87.619,7407.598 87.619,7408.718 C87.619,7412.646 89.954,7413.526 92.175,7413.785 C91.889,7414.041 91.63,7414.493 91.54,7415.156 C90.97,7415.418 89.522,7415.871 88.63,7414.304 C88.63,7414.304 88.101,7413.319 87.097,7413.247 C87.097,7413.247 86.122,7413.234 87.029,7413.87 C87.029,7413.87 87.684,7414.185 88.139,7415.37 C88.139,7415.37 88.726,7417.2 91.508,7416.58 C91.513,7417.437 91.522,7418.245 91.522,7418.489 C91.522,7418.76 91.338,7419.077 90.839,7418.982 C86.865,7417.627 84,7413.783 84,7409.253 C84,7403.59 88.478,7399 94,7399" id="github-[#142]">

</path>
            </g>
        </g>
    </g>
</svg>

portfolio/templates/partials/git_logo2.html
<svg width="50px" height="50px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      
    <title>github [#142]</title>
    <desc>Created with Sketch.</desc>
    <defs>

</defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Dribbble-Light-Preview" transform="translate(-140.000000, -7559.000000)" fill="#000000">
            <g id="icons" transform="translate(56.000000, 160.000000)">
                <path d="M94,7399 C99.523,7399 104,7403.59 104,7409.253 C104,7413.782 101.138,7417.624 97.167,7418.981 C96.66,7419.082 96.48,7418.762 96.48,7418.489 C96.48,7418.151 96.492,7417.047 96.492,7415.675 C96.492,7414.719 96.172,7414.095 95.813,7413.777 C98.04,7413.523 100.38,7412.656 100.38,7408.718 C100.38,7407.598 99.992,7406.684 99.35,7405.966 C99.454,7405.707 99.797,7404.664 99.252,7403.252 C99.252,7403.252 98.414,7402.977 96.505,7404.303 C95.706,7404.076 94.85,7403.962 94,7403.958 C93.15,7403.962 92.295,7404.076 91.497,7404.303 C89.586,7402.977 88.746,7403.252 88.746,7403.252 C88.203,7404.664 88.546,7405.707 88.649,7405.966 C88.01,7406.684 87.619,7407.598 87.619,7408.718 C87.619,7412.646 89.954,7413.526 92.175,7413.785 C91.889,7414.041 91.63,7414.493 91.54,7415.156 C90.97,7415.418 89.522,7415.871 88.63,7414.304 C88.63,7414.304 88.101,7413.319 87.097,7413.247 C87.097,7413.247 86.122,7413.234 87.029,7413.87 C87.029,7413.87 87.684,7414.185 88.139,7415.37 C88.139,7415.37 88.726,7417.2 91.508,7416.58 C91.513,7417.437 91.522,7418.245 91.522,7418.489 C91.522,7418.76 91.338,7419.077 90.839,7418.982 C86.865,7417.627 84,7413.783 84,7409.253 C84,7403.59 88.478,7399 94,7399" id="github-[#142]">

</path>
            </g>
        </g>
    </g>
</svg>

portfolio/templates/partials/html_css_logo.html
<svg
  width="30px"
  height="30px"
  viewBox="0 0 32 32"
  fill="none"
  xmlns="http://www.w3.org/2000/svg"
>
  <path d="M6 28L4 3H28L26 28L16 31L6 28Z" fill="#E44D26" />
  <path d="M26 5H16V29.5L24 27L26 5Z" fill="#F16529" />
  <path
    d="M9.5 17.5L8.5 8H24L23.5 11H11.5L12 14.5H23L22 24L16 26L10 24L9.5 19H12.5L13 21.5L16 22.5L19 21.5L19.5 17.5H9.5Z"
    fill="white"
  />
</svg>
<svg
  width="30px"
  height="30px"
  viewBox="0 0 32 32"
  xmlns="http://www.w3.org/2000/svg"
>
  <title>file_type_css</title>
  <polygon
    points="5.902 27.201 3.656 2 28.344 2 26.095 27.197 15.985 30 5.902 27.201"
    style="fill: #1572b6"
  />
  <polygon
    points="16 27.858 24.17 25.593 26.092 4.061 16 4.061 16 27.858"
    style="fill: #33a9dc"
  />
  <polygon
    points="16 13.191 20.09 13.191 20.372 10.026 16 10.026 16 6.935 16.011 6.935 23.75 6.935 23.676 7.764 22.917 16.282 16 16.282 16 13.191"
    style="fill: #fff"
  />
  <polygon
    points="16.019 21.218 16.005 21.222 12.563 20.292 12.343 17.827 10.67 17.827 9.24 17.827 9.673 22.68 16.004 24.438 16.019 24.434 16.019 21.218"
    style="fill: #ebebeb"
  />
  <polygon
    points="19.827 16.151 19.455 20.29 16.008 21.22 16.008 24.436 22.344 22.68 22.391 22.158 22.928 16.151 19.827 16.151"
    style="fill: #fff"
  />
  <polygon
    points="16.011 6.935 16.011 8.855 16.011 10.018 16.011 10.026 8.555 10.026 8.555 10.026 8.545 10.026 8.483 9.331 8.342 7.764 8.268 6.935 16.011 6.935"
    style="fill: #ebebeb"
  />
  <polygon
    points="16 13.191 16 15.111 16 16.274 16 16.282 12.611 16.282 12.611 16.282 12.601 16.282 12.539 15.587 12.399 14.02 12.325 13.191 16 13.191"
    style="fill: #ebebeb"
  />
</svg>

portfolio/templates/partials/linkedin_logo.html
<svg width="57px" height="57px" viewBox="0 -2 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="2" y="2" width="28" height="28" rx="14" fill="#444444"/>
    <path d="M12.6186 9.69215C12.6186 10.6267 11.8085 11.3843 10.8093 11.3843C9.81004 11.3843 9 10.6267 9 9.69215C9 8.7576 9.81004 8 10.8093 8C11.8085 8 12.6186 8.7576 12.6186 9.69215Z" fill="white"/>
    <path d="M9.24742 12.6281H12.3402V22H9.24742V12.6281Z" fill="white"/>
    <path d="M17.3196 12.6281H14.2268V22H17.3196C17.3196 22 17.3196 19.0496 17.3196 17.2049C17.3196 16.0976 17.6977 14.9855 19.2062 14.9855C20.911 14.9855 20.9008 16.4345 20.8928 17.5571C20.8824 19.0244 20.9072 20.5219 20.9072 22H24V17.0537C23.9738 13.8954 23.1508 12.4401 20.4433 12.4401C18.8354 12.4401 17.8387 13.1701 17.3196 13.8305V12.6281Z" fill="white"/>
</svg>

portfolio/templates/partials/logo_django.html
<svg width="27px" height="27px" viewBox="0 0 256 256" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid">
    <g>
        <rect fill="#092E20" x="0" y="0" width="256" height="256" rx="28">
    
</rect>
        <path d="M186.377012,94.197636 L186.377012,160.424478 C186.377012,183.243286 184.707519,194.187745 179.699037,203.649406 C175.060358,212.741266 168.937684,218.490548 156.323731,224.798721 L129.794937,212.183571 C142.410087,206.247593 148.531564,201.05481 152.427049,193.074749 C156.509231,184.91278 157.808923,175.451119 157.808923,150.593015 L157.808923,94.197636 L186.377012,94.197636 Z M140.928486,50.0787207 L140.928486,182.316986 C126.272844,185.099476 115.512688,186.212472 103.826231,186.212472 C68.9487718,186.212472 50.7686431,170.445031 50.7686431,140.205054 C50.7686431,111.079269 70.0629644,92.1583404 99.9295492,92.1583404 C104.567032,92.1583404 108.091519,92.5281423 112.359199,93.6411381 L112.359199,50.0787207 L140.928486,50.0787207 Z M102.713236,115.160254 C88.243093,115.160254 79.8944275,124.065418 79.8944275,139.647359 C79.8944275,154.860696 87.8720944,163.208164 102.527736,163.208164 C105.680028,163.208164 108.278215,163.022665 112.359199,162.467364 L112.359199,116.643052 C109.020212,115.531253 106.237722,115.160254 102.713236,115.160254 Z M186.377012,50.2307105 L186.377012,79.5419941 L157.808923,79.5419941 L157.808923,50.2307105 L186.377012,50.2307105 Z" fill="#FFFFFD">
</path>
    </g>
</svg>

portfolio/templates/partials/logo_js.html
<?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg
  width="25px"
  height="25px"
  viewBox="0 0 256 256"
  xmlns="http://www.w3.org/2000/svg"
  preserveAspectRatio="xMinYMin meet"
>
  <path d="M0 0h256v256H0V0z" fill="#F7DF1E" />
  <path
    d="M67.312 213.932l19.59-11.856c3.78 6.701 7.218 12.371 15.465 12.371 7.905 0 12.89-3.092 12.89-15.12v-81.798h24.057v82.138c0 24.917-14.606 36.259-35.916 36.259-19.245 0-30.416-9.967-36.087-21.996M152.381 211.354l19.588-11.341c5.157 8.421 11.859 14.607 23.715 14.607 9.969 0 16.325-4.984 16.325-11.858 0-8.248-6.53-11.17-17.528-15.98l-6.013-2.58c-17.357-7.387-28.87-16.667-28.87-36.257 0-18.044 13.747-31.792 35.228-31.792 15.294 0 26.292 5.328 34.196 19.247L210.29 147.43c-4.125-7.389-8.591-10.31-15.465-10.31-7.046 0-11.514 4.468-11.514 10.31 0 7.217 4.468 10.14 14.778 14.608l6.014 2.577c20.45 8.765 31.963 17.7 31.963 37.804 0 21.654-17.012 33.51-39.867 33.51-22.339 0-36.774-10.654-43.819-24.574"
  />
</svg>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Leonardo Rodriguez</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/CV1.2.pdf' %}" target="_blank">Download CV</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>